"use client";

import { useState } from "react";
import Link from "next/link";
import { initials } from "@/lib/util";
import { loadAssessmentDetail, type AssessmentDetail, type SectionScore } from "./actions";

export type SuiteRow = {
  id: string;
  name: string;
  kind: string;
  category: string;
  status: string;
  team: string | null;
  respondents: number;
  date: string;
};

export type Kpi = { big: string; title: string; sub: string };

type View = "overview" | "detail";
type DetailTab = "info" | "questions" | "responses" | "results" | "workshop" | "activity";

const BAND_VARS = ["var(--rust)", "var(--amber)", "var(--green)"] as const;
const BAND_LABEL = ["Below band", "Mid band", "Above band"] as const;

function statusPill(status: string) {
  if (status === "open") return <span className="pill sm open">Open</span>;
  if (status === "closed") return <span className="pill sm draft">Closed</span>;
  return <span className="pill sm internal">{status || "Draft"}</span>;
}

function fmtDate(iso: string) {
  const d = new Date(iso);
  return isNaN(d.getTime()) ? "" : d.toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" });
}

function fmtDateTime(iso: string) {
  const d = new Date(iso);
  return isNaN(d.getTime()) ? "" : d.toLocaleString(undefined, { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" });
}

export function AssessmentSuite({ rows, kpis }: { rows: SuiteRow[]; kpis: Kpi[] }) {
  const [view, setView] = useState<View>("overview");
  const [active, setActive] = useState<SuiteRow | null>(null);
  const [tab, setTab] = useState<DetailTab>("info");
  const [detail, setDetail] = useState<AssessmentDetail | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [query, setQuery] = useState("");

  async function open(row: SuiteRow) {
    setActive(row);
    setTab("info");
    setDetail(null);
    setError(null);
    setView("overview"); // keep list mounted under the load
    setLoading(true);
    const res = await loadAssessmentDetail(row.id);
    setLoading(false);
    if (res.error || !res.detail) {
      setError(res.error ?? "Could not load this assessment.");
      setView("detail");
      return;
    }
    setDetail(res.detail);
    setView("detail");
    if (typeof window !== "undefined") window.scrollTo(0, 0);
  }

  function back() {
    setView("overview");
    setActive(null);
    setDetail(null);
  }

  // --- printable report (browser print → Save as PDF), same pattern as the library ---
  function exportReport() {
    if (!active || !detail) return;
    const esc = (s: string) => s.replace(/[&<>]/g, (m) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" }[m] as string));
    const bars = detail.scores
      .map((s) => {
        const color = s.band === 0 ? "#b8584a" : s.band === 1 ? "#a8862f" : "#3f7d5a";
        return `<div class="row"><span class="nm">${esc(s.label)}</span><span class="track"><span class="fill" style="width:${s.pct.toFixed(0)}%;background:${color}"></span></span><span class="sc" style="color:${color}">${s.mean.toFixed(1)}</span></div>`;
      })
      .join("");
    const html = `<!doctype html><html><head><meta charset="utf-8"><title>${esc(active.name)} — report</title>
<style>body{font-family:Georgia,'Times New Roman',serif;color:#1f2421;margin:46px;line-height:1.55}
h1{font-size:24px;margin:0 0 2px}.meta{color:#6b726c;font-size:13px;margin-bottom:24px}
.row{display:flex;align-items:center;gap:12px;margin:9px 0}.nm{width:200px;font-size:13px}
.track{flex:1;height:9px;border-radius:999px;background:#eee;overflow:hidden}.fill{display:block;height:100%;border-radius:999px}
.sc{width:34px;text-align:right;font-weight:700;font-size:13px}
.foot{color:#7a817b;font-size:12px;margin-top:24px;border-top:1px solid #e3e6e2;padding-top:10px}</style>
</head><body><h1>${esc(active.name)}</h1>
<div class="meta">${active.team ? esc(active.team) + " · " : ""}${fmtDate(active.date)} · ${detail.respondents} responses</div>
${detail.scores.length ? bars : "<p>Results are hidden until the minimum number of people have responded.</p>"}
<div class="foot">Overall ${detail.overall != null ? detail.overall.toFixed(1) : "—"} · scale ${detail.scale.min}–${detail.scale.max} · generated by Owntheagenda</div>
<script>window.onload=function(){window.print();}</script></body></html>`;
    const w = window.open("", "_blank", "width=820,height=1000");
    if (!w) return;
    w.document.write(html);
    w.document.close();
  }

  // ---------------- OVERVIEW ----------------
  if (view === "overview") {
    const filtered = query.trim()
      ? rows.filter((r) => `${r.name} ${r.team ?? ""}`.toLowerCase().includes(query.trim().toLowerCase()))
      : rows;
    return (
      <>
        <div className="a-phead">
          <div>
            <div className="a-pt">Assessment suite</div>
            <div className="a-ps">Every assessment across your teams — status, responses and where a section falls below the healthy band.</div>
          </div>
          <div className="a-pr">
            <Link className="btn-sec" href="/assessments/library">Instrument library</Link>
          </div>
        </div>

        <div className="as-kpis">
          {kpis.map((k, i) => (
            <div className="as-kpi" key={i}>
              <div className="as-kpi-big">{k.big}</div>
              <div className="as-kpi-title">{k.title}</div>
              <div className="as-kpi-sub">{k.sub}</div>
            </div>
          ))}
        </div>

        <div className="tbl-card">
          <div className="as-tablehead">
            <span className="cat-head" style={{ margin: 0 }}>All assessments <span className="n">{rows.length}</span></span>
            <input
              className="inp as-search"
              placeholder="Search title, team…"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
            />
          </div>
          {filtered.length ? (
            <table className="tbl">
              <thead>
                <tr>
                  <th>Assessment</th>
                  <th style={{ width: 110 }}>Type</th>
                  <th style={{ width: 110 }}>Status</th>
                  <th style={{ width: 120 }}>Responses</th>
                  <th style={{ width: 160 }}>Team</th>
                  <th style={{ width: 70 }} />
                </tr>
              </thead>
              <tbody>
                {filtered.map((r) => (
                  <tr key={r.id} onClick={() => open(r)} style={{ cursor: "pointer" }}>
                    <td>
                      <span style={{ fontWeight: 600 }}>{r.name}</span>
                      <small style={{ display: "block", color: "var(--faint)" }}>{fmtDate(r.date)}</small>
                    </td>
                    <td style={{ color: "var(--muted)" }}>{r.category}</td>
                    <td>{statusPill(r.status)}</td>
                    <td style={{ fontVariantNumeric: "tabular-nums" }}>{r.respondents}</td>
                    <td style={{ color: "var(--muted)" }}>
                      {r.team ? (
                        <span className="person" style={{ fontWeight: 500 }}>
                          <span className="av sm green">{initials(r.team)}</span>
                          {r.team}
                        </span>
                      ) : "—"}
                    </td>
                    <td className="r"><span className="linkbtn">Open ›</span></td>
                  </tr>
                ))}
              </tbody>
            </table>
          ) : (
            <div className="empty">{rows.length ? "No assessments match your search." : "No assessments run yet — open a team assessment from the instrument library to get started."}</div>
          )}
        </div>
        {loading ? <div className="a-note" style={{ marginTop: 14 }}>Loading assessment…</div> : null}
      </>
    );
  }

  // ---------------- DETAIL ----------------
  return (
    <>
      <div className="a-phead">
        <button className="a-back" onClick={back} aria-label="Back">‹</button>
        <div>
          <div className="a-pt">{active?.name}</div>
          <div className="a-ps">
            {active?.team ? `${active.team} · ` : ""}{active ? fmtDate(active.date) : ""}
            {detail ? ` · ${detail.respondents} responses` : ""}
          </div>
        </div>
        <div className="a-pr">
          {active ? statusPill(active.status) : null}
          {detail && detail.scores.length ? <button className="btn-sec" onClick={exportReport}>⤓ Export report</button> : null}
          <Link className="btn-prim" href="/workshops">Open workshop →</Link>
        </div>
      </div>

      {error ? <div className="a-note" style={{ marginTop: 14 }}>{error}</div> : null}

      {detail ? (
        <>
          <nav className="as-tabs" aria-label="Assessment detail">
            {([
              ["info", "Information"],
              ["questions", "Questions"],
              ["responses", "Responses"],
              ["results", "Results"],
              ["workshop", "Workshop"],
              ["activity", "Activity"],
            ] as [DetailTab, string][]).map(([key, label]) => (
              <button key={key} className={`as-tab${tab === key ? " on" : ""}`} onClick={() => setTab(key)}>{label}</button>
            ))}
          </nav>

          {tab === "info" ? (
            <div className="a-ov">
              <div className="a-ovcard">
                <h3>About this assessment</h3>
                <p>
                  An anonymous {detail.instrumentName} survey. {detail.questions.length} questions across {detail.sections.length} {detail.sections.length === 1 ? "section" : "sections"},
                  scored on a {detail.scale.min}–{detail.scale.max} scale. Results stay hidden until enough people respond, then surface as section means — where a section falls below the healthy band, it is a candidate for a follow-up workshop.
                </p>
                <div className="a-seclbl">Sections</div>
                <div className="a-dimlist">{detail.sections.map((s) => <span className="a-dimchip" key={s.key}>{s.label}</span>)}</div>
              </div>
              <div className="a-ovcard">
                <h3>Details</h3>
                <div className="a-facts">
                  <Fact k="Type" v={`${active?.category} · ${detail.questions.length}Q`} />
                  <Fact k="Sections" v={String(detail.sections.length)} />
                  <Fact k="Scale" v={`${detail.scale.min}–${detail.scale.max}`} />
                  <Fact k="Anonymous" v="Yes" />
                  <Fact k="Team" v={active?.team ?? "—"} />
                  <Fact k="Responses" v={String(detail.respondents)} />
                </div>
              </div>
            </div>
          ) : null}

          {tab === "questions" ? (
            <div className="tbl-card">
              {detail.sections.map((sec) => (
                <div key={sec.key}>
                  <div className="as-qgroup">{sec.label} <span className="n">{sec.count}</span></div>
                  {detail.questions.filter((q) => q.dimension === sec.key).map((q, i) => (
                    <div className="as-qrow" key={q.key}>
                      <span className="as-qn">{i + 1}</span>
                      <span>{q.text}</span>
                    </div>
                  ))}
                </div>
              ))}
            </div>
          ) : null}

          {tab === "responses" ? (
            <div className="a-ovcard">
              <h3>Responses <span style={{ fontWeight: 500, color: "var(--faint)" }}>· {detail.respondents}</span></h3>
              {detail.respondents ? (
                <>
                  <p>
                    {detail.respondents} {detail.respondents === 1 ? "person has" : "people have"} responded.
                    {detail.masked
                      ? " Individual submissions stay hidden until the minimum number of responses is reached — answers are never attributed to a person."
                      : " Responses are anonymous in aggregate; no answer is tied to a person."}
                  </p>
                  {detail.submissions.length ? (
                    <table className="tbl" style={{ marginTop: 6 }}>
                      <thead>
                        <tr><th>Respondent</th><th style={{ width: 180 }}>Submitted</th></tr>
                      </thead>
                      <tbody>
                        {detail.submissions.map((when, i) => (
                          <tr key={i}>
                            <td><span className="person" style={{ fontWeight: 500 }}><span className="av sm">?</span>Anonymous respondent</span></td>
                            <td style={{ color: "var(--muted)", fontVariantNumeric: "tabular-nums" }}>{fmtDateTime(when)}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  ) : null}
                </>
              ) : (
                <p className="muted">No responses yet. {active?.status === "open" ? "The assessment is open — results will appear here as people respond." : "This assessment is closed with no responses."}</p>
              )}
            </div>
          ) : null}

          {tab === "results" ? (
            <SectionResults detail={detail} />
          ) : null}

          {tab === "workshop" ? (
            <div className="as-workshop">
              <div className="as-ws-eyebrow">{detail.linkedWorkshop ? "Linked workshop" : "Follow-up workshop"}</div>
              <div className="as-ws-title">
                {detail.linkedWorkshop
                  ? detail.linkedWorkshop.title
                  : detail.belowCount
                    ? `${detail.belowCount} ${detail.belowCount === 1 ? "section is" : "sections are"} below the healthy band`
                    : "No section is below the band"}
              </div>
              <p className="as-ws-sub">
                {detail.linkedWorkshop
                  ? "This assessment is carried into a workshop — open it to review the agenda, run the session and track the measures agreed."
                  : detail.belowCount
                    ? "A targeted workshop helps the team work through the lowest-scoring sections together — diagnose causes, agree measures and assign owners."
                    : "Scores look healthy. You can still run a workshop to build on strengths or revisit a theme."}
              </p>
              {detail.linkedWorkshop ? (
                <Link className="btn-prim" href={`/workshops/${detail.linkedWorkshop.id}/overview`}>Open workshop →</Link>
              ) : (
                <Link className="btn-prim" href="/workshops">Start a workshop →</Link>
              )}
            </div>
          ) : null}

          {tab === "activity" ? (
            <div className="a-ovcard">
              <h3>Activity</h3>
              {detail.activity.length ? (
                <div className="wsd-log">
                  {detail.activity.map((e) => (
                    <div className="wsd-log-row" key={e.id}>
                      <span className="wsd-log-dot" />
                      <div>
                        <div className="wsd-log-l">{e.label}</div>
                        <div className="wsd-log-m">{e.actor} · {fmtDateTime(e.at)}</div>
                      </div>
                    </div>
                  ))}
                </div>
              ) : (
                <p className="muted">No activity recorded yet. Lifecycle events (opened, closed) appear here — visible to workspace admins.</p>
              )}
            </div>
          ) : null}
        </>
      ) : loading ? (
        <div className="a-note" style={{ marginTop: 14 }}>Loading assessment…</div>
      ) : null}
    </>
  );
}

function SectionResults({ detail }: { detail: AssessmentDetail }) {
  if (detail.masked || !detail.scores.length) {
    return (
      <div className="empty">
        Results stay hidden until at least the minimum number of people respond — individual answers are never shown.
        {detail.respondents ? ` (${detail.respondents} so far.)` : ""}
      </div>
    );
  }
  return (
    <>
      <div className="as-kpis" style={{ marginBottom: 16 }}>
        <div className="as-kpi"><div className="as-kpi-big">{detail.overall?.toFixed(1)}</div><div className="as-kpi-title">Overall mean</div><div className="as-kpi-sub">scale {detail.scale.min}–{detail.scale.max}</div></div>
        <div className="as-kpi"><div className="as-kpi-big" style={{ color: detail.belowCount ? "var(--rust)" : "var(--ink)" }}>{detail.belowCount}</div><div className="as-kpi-title">Sections below band</div><div className="as-kpi-sub">candidates for a workshop</div></div>
        <div className="as-kpi"><div className="as-kpi-big">{detail.respondents}</div><div className="as-kpi-title">Responses</div><div className="as-kpi-sub">anonymous in aggregate</div></div>
        <div className="as-kpi"><div className="as-kpi-big">{detail.lowestLabel ? detail.scores.find((s) => s.label === detail.lowestLabel)?.mean.toFixed(1) : "—"}</div><div className="as-kpi-title">Lowest section</div><div className="as-kpi-sub">{detail.lowestLabel ?? "—"}</div></div>
      </div>
      <div className="a-ovcard">
        <h3>Section scores</h3>
        {detail.scores.map((s) => <ScoreBar key={s.key} s={s} />)}
        <div className="as-legend">
          <span><span className="as-sw" style={{ background: "var(--rust)" }} />{BAND_LABEL[0]}</span>
          <span><span className="as-sw" style={{ background: "var(--amber)" }} />{BAND_LABEL[1]}</span>
          <span><span className="as-sw" style={{ background: "var(--green)" }} />{BAND_LABEL[2]}</span>
        </div>
      </div>
    </>
  );
}

function ScoreBar({ s }: { s: SectionScore }) {
  const color = BAND_VARS[s.band];
  return (
    <div className="as-scorerow">
      <span className="as-scorename">{s.label}</span>
      <span className="as-scoretrack"><span className="as-scorefill" style={{ width: `${s.pct.toFixed(0)}%`, background: color }} /></span>
      <span className="as-scoreval" style={{ color }}>{s.mean.toFixed(1)}</span>
    </div>
  );
}

function Fact({ k, v }: { k: string; v: string }) {
  return <div className="a-fact"><span className="k">{k}</span><span className="v">{v}</span></div>;
}
