insert into public.assessment_category (instrument, code, name, ord) values
 ('leadership_effectiveness','input','Input Factors (Preconditions)',1),
 ('leadership_effectiveness','process','Process Factors (Meeting & Behavioral Dynamics)',2),
 ('leadership_effectiveness','emergent','Emergent States (Relational Climate)',3),
 ('leadership_effectiveness','output','Output Factors (Effectiveness & ROI)',4)
on conflict (instrument, code) do nothing;

insert into public.assessment_facet (category_id, code, name, ord)
select c.id, f.code, f.name, f.ord
from (values
 ('input','purpose','Clear Team Purpose',1),
 ('input','tasks','Appropriate Tasks (Strategic Focus)',2),
 ('input','composition','Team Composition',3),
 ('input','size','Team Size',4),
 ('input','environment','Supportive Environment',5),
 ('process','agenda','Goal-Clarified Agenda',1),
 ('process','communication','Focused Communication',2),
 ('process','dialogue','Dialogical & Exploratory Behavior',3),
 ('process','task_conflict','Task Conflict',4),
 ('process','rel_conflict','Absence of Relationship Conflict',5),
 ('process','political','Absence of Political Behavior',6),
 ('process','boundary','Boundary Spanning',7),
 ('process','learning','Team Learning Behavior',8),
 ('process','leadership','Effective Team Leadership',9),
 ('emergent','psych_safety','Psychological Safety',1),
 ('emergent','cohesion','Team Cohesion',2),
 ('emergent','trust','Interpersonal Trust',3),
 ('emergent','potency','Team Potency',4),
 ('output','task_performance','Task Performance',1),
 ('output','wellbeing','Relationship & Well-being',2),
 ('output','viability','Organizational Viability',3)
) as f(cat, code, name, ord)
join public.assessment_category c on c.code = f.cat and c.instrument = 'leadership_effectiveness'
on conflict (code) do nothing;

insert into public.assessment_question (facet_id, item_key, ord, text, reverse_scored)
select fa.id, q.item_key, q.ord, q.text, q.reverse
from (values
 ('purpose','purpose_1',1,'Our leadership team has a clearly defined and shared understanding of our overarching purpose.',false),
 ('purpose','purpose_2',2,'We all agree on what unique value this team is supposed to deliver to the organization.',false),
 ('purpose','purpose_3',3,'We have a clear boundary between what we must handle as a team and what belongs in individual departments.',false),
 ('tasks','tasks_1',4,'The items on our agenda are genuinely critical to the strategic direction of the organization.',false),
 ('tasks','tasks_2',5,'We spend too much time discussing operational details that should be resolved outside this meeting.',true),
 ('tasks','tasks_3',6,'The issues we process require true cross-functional collaboration to be solved.',false),
 ('composition','composition_1',7,'This team consists of the right mix of professional expertise to solve our most complex challenges.',false),
 ('composition','composition_2',8,'We have enough cognitive diversity (different ways of thinking) to avoid groupthink.',false),
 ('composition','composition_3',9,'The members in this room have the necessary formal authority to implement the decisions we make.',false),
 ('size','size_1',10,'The size of this leadership team makes it difficult to have meaningful, deep discussions.',true),
 ('size','size_2',11,'There are people in this team whose presence is not strictly necessary for our core mandate.',true),
 ('size','size_3',12,'Our team size is perfectly balanced—large enough to have the right perspectives, but small enough to be efficient.',false),
 ('environment','environment_1',13,'The organization''s incentive and reward systems promote our collective success rather than individual competition.',false),
 ('environment','environment_2',14,'We have access to all the necessary information and resources required to make high-level strategic decisions.',false),
 ('environment','environment_3',15,'Our board (or higher management) actively supports the mandate and authority of this leadership team.',false),
 ('agenda','agenda_1',16,'Before we discuss an agenda item, it is entirely clear what we are supposed to produce (e.g., a decision, a brainstorm, an orientation).',false),
 ('agenda','agenda_2',17,'The preparation materials clearly state the expected outcome of each discussion.',false),
 ('agenda','agenda_3',18,'We frequently finish discussing a topic without being clear on what we actually just agreed upon.',true),
 ('communication','communication_1',19,'Team members stick strictly to the topic being discussed.',false),
 ('communication','communication_2',20,'Certain members of this team have a habit of going off on lengthy, irrelevant monologues.',true),
 ('communication','communication_3',21,'We are highly efficient at moving from open discussion to a concrete conclusion.',false),
 ('dialogue','dialogue_1',22,'Team members actively ask questions to understand the reasoning behind each other''s opinions.',false),
 ('dialogue','dialogue_2',23,'We actively build upon each other''s ideas rather than just waiting for our turn to speak.',false),
 ('dialogue','dialogue_3',24,'Members of this team are good at summarizing and confirming they understand a colleague''s point before disagreeing with it.',false),
 ('task_conflict','task_conflict_1',25,'We actively challenge each other''s viewpoints on strategic issues.',false),
 ('task_conflict','task_conflict_2',26,'We view professional disagreements as a vital tool to reach the best possible decisions.',false),
 ('task_conflict','task_conflict_3',27,'Our discussions often involve a rigorous, healthy debate about the work.',false),
 ('rel_conflict','rel_conflict_1',28,'Disagreements in our meetings often feel personal rather than professional.',true),
 ('rel_conflict','rel_conflict_2',29,'There is noticeable interpersonal tension and irritation among certain members of this team.',true),
 ('rel_conflict','rel_conflict_3',30,'People in this team sometimes hold grudges or let past conflicts influence current discussions.',true),
 ('political','political_1',31,'Important decisions are often finalized in the corridors before the actual team meeting takes place.',true),
 ('political','political_2',32,'Team members sometimes form hidden alliances to push their own agendas.',true),
 ('political','political_3',33,'People are transparent about their motives when advocating for a specific decision.',false),
 ('boundary','boundary_1',34,'We systematically gather intelligence and feedback from the rest of the organization to inform our decisions.',false),
 ('boundary','boundary_2',35,'We proactively align our team''s work with the needs of other departments and stakeholders.',false),
 ('boundary','boundary_3',36,'Our team is well-informed about external market trends and competitor movements.',false),
 ('learning','learning_1',37,'We regularly set aside time to evaluate how we collaborate in our meetings.',false),
 ('learning','learning_2',38,'When we identify a flaw in our team dynamics, we make concrete adjustments to fix it.',false),
 ('learning','learning_3',39,'Team members proactively ask each other for feedback on their contributions to the team.',false),
 ('leadership','leadership_1',40,'The team leader effectively structures our meetings to ensure we focus on the right things.',false),
 ('leadership','leadership_2',41,'The team leader is skilled at drawing out the opinions of quieter members and balancing participation.',false),
 ('leadership','leadership_3',42,'The team leader effectively stops irrelevant tangents and keeps us on track.',false),
 ('psych_safety','psych_safety_1',43,'If you make a mistake on this team, it is often held against you.',true),
 ('psych_safety','psych_safety_2',44,'Members of this team are able to bring up problems and tough, uncomfortable issues.',false),
 ('psych_safety','psych_safety_3',45,'It is safe to take an interpersonal risk (like admitting ignorance or proposing a wild idea) on this team.',false),
 ('cohesion','cohesion_1',46,'There is a strong sense of unity and shared identity within this leadership team.',false),
 ('cohesion','cohesion_2',47,'Team members prioritize the success of the overall organization above the success of their own departments.',false),
 ('cohesion','cohesion_3',48,'I feel a strong sense of belonging to this leadership team.',false),
 ('trust','trust_1',49,'I trust that my colleagues in the leadership team will deliver on their commitments.',false),
 ('trust','trust_2',50,'Team members assume positive intent when colleagues challenge them.',false),
 ('trust','trust_3',51,'I have deep confidence in the professional competence of the other members of this team.',false),
 ('potency','potency_1',52,'This team shares a collective belief that we can overcome any organizational challenge, no matter how difficult.',false),
 ('potency','potency_2',53,'We have high expectations of what we can achieve together.',false),
 ('potency','potency_3',54,'Even when facing major setbacks, this team remains confident in our collective ability to succeed.',false),
 ('task_performance','task_performance_1',55,'The decisions made by this team consistently create measurable, strategic value for the organization.',false),
 ('task_performance','task_performance_2',56,'We make decisions at the right time, without unnecessary delays or endless postponement.',false),
 ('task_performance','task_performance_3',57,'The strategies we agree upon in this room are successfully executed and implemented in the wider organization.',false),
 ('wellbeing','wellbeing_1',58,'Being a member of this leadership team increases my motivation and energy for my daily work.',false),
 ('wellbeing','wellbeing_2',59,'The team environment actively supports my personal and professional development as a leader.',false),
 ('wellbeing','wellbeing_3',60,'Attending our leadership meetings drains my energy and frustrates me.',true),
 ('viability','viability_1',61,'Our team is becoming better equipped to handle complex organizational crises today than we were six months ago.',false),
 ('viability','viability_2',62,'Our ability to cooperate and solve problems together is continuously improving.',false),
 ('viability','viability_3',63,'I believe this team will continue to function highly effectively in the future.',false)
) as q(facet, item_key, ord, text, reverse)
join public.assessment_facet fa on fa.code = q.facet
on conflict (item_key) do nothing;
