-- Strategy Health (team): Strategy Quality (Rumelt) vs Execution Readiness
-- (Speculand Implementation Compass / BSC). Carries a 2×2 quadrant config.
insert into public.assessment_template (workspace_id, key, name, category, scope, source, description, definition)
select null, 'strategy_health', 'Strategy Health — Quality vs Readiness', 'strategy', 'team',
  'Grounded in Rumelt (Good Strategy/Bad Strategy) + Speculand Implementation Compass; Kaplan & Norton BSC',
  'Separates whether the strategy is good (quality) from whether you can execute it (readiness), plotted on a 2x2.',
  $j${"scale":{"min":1,"max":7,"minLabel":"Strongly disagree","maxLabel":"Strongly agree"},"strengthDimension":"quality","quadrant":{"x":"quality","y":"readiness","xLabel":"Strategy quality","yLabel":"Execution readiness","q":{"ll":"Back to basics","hl":"Strong plan, not ready","lh":"Busy but adrift","hh":"Ready to win"}},"dimensions":[{"key":"quality","label":"Strategy quality","blurb":"Is the strategy itself good — clear diagnosis, hard choices, coherent action?"},{"key":"readiness","label":"Execution readiness","blurb":"Can we actually execute it — resourced, owned, on a cadence, capable?"}],"items":[{"key":"q_1","dimension":"quality","text":"We have a clear, honest diagnosis of the key challenge we face."},{"key":"q_2","dimension":"quality","text":"Our strategy makes hard choices about what we will not do."},{"key":"q_3","dimension":"quality","text":"Our strategy has a coherent guiding approach, not just a list of goals."},{"key":"q_4","dimension":"quality","text":"Our priorities are focused, not spread thin across too many initiatives."},{"key":"q_5","dimension":"quality","text":"Our strategy is grounded in real evidence about customers and competitors."},{"key":"r_1","dimension":"readiness","text":"The resources needed to execute (people, budget, time) are actually committed."},{"key":"r_2","dimension":"readiness","text":"Every major initiative has a clear, accountable owner."},{"key":"r_3","dimension":"readiness","text":"We review progress on the strategy on a regular cadence."},{"key":"r_4","dimension":"readiness","text":"We have the capabilities and skills the strategy requires."},{"key":"r_5","dimension":"readiness","text":"Day-to-day priorities are aligned with the strategy."}]}$j$::jsonb
where not exists (select 1 from public.assessment_template where workspace_id is null and key='strategy_health');

-- Strategy Kernel (individual): Rumelt's kernel — diagnosis / guiding policy / coherent action.
insert into public.assessment_template (workspace_id, key, name, category, scope, source, description, definition)
select null, 'strategy_kernel', 'Strategy Kernel Check', 'strategy', 'individual',
  'Grounded in Rumelt''s kernel of good strategy (diagnosis, guiding policy, coherent action)',
  'A fast solo check on the three parts of a good strategy kernel.',
  $j${"scale":{"min":1,"max":7,"minLabel":"Strongly disagree","maxLabel":"Strongly agree"},"strengthDimension":"diagnosis","dimensions":[{"key":"diagnosis","label":"Diagnosis","blurb":"Do you name the real challenge, not just symptoms?"},{"key":"policy","label":"Guiding policy","blurb":"Do you have a clear approach that makes real choices?"},{"key":"action","label":"Coherent action","blurb":"Do your actions reinforce each other and stay focused?"}],"items":[{"key":"d_1","dimension":"diagnosis","text":"I can clearly name the single most important challenge my strategy addresses."},{"key":"d_2","dimension":"diagnosis","text":"I have diagnosed the root cause, not just the symptoms."},{"key":"p_1","dimension":"policy","text":"I have a clear guiding approach for overcoming that challenge."},{"key":"p_2","dimension":"policy","text":"My approach makes a real choice — it rules some options out."},{"key":"a_1","dimension":"action","text":"My strategy translates into a coherent set of actions that reinforce each other."},{"key":"a_2","dimension":"action","text":"My actions are focused on a few priorities, not scattered."}]}$j$::jsonb
where not exists (select 1 from public.assessment_template where workspace_id is null and key='strategy_kernel');

-- Manager Skills (individual): manager self-assessment across four practice areas.
insert into public.assessment_template (workspace_id, key, name, category, scope, source, description, definition)
select null, 'manager_skills', 'Manager Skills Self-Check', 'leadership', 'individual',
  'OwnTheAgenda original · core management practices (direction, coaching, communication, accountability)',
  'A personal read on your management practice across four areas.',
  $j${"scale":{"min":1,"max":7,"minLabel":"Strongly disagree","maxLabel":"Strongly agree"},"strengthDimension":"coaching","dimensions":[{"key":"direction","label":"Direction & goals","blurb":"Setting clear goals and connecting work to the bigger picture."},{"key":"coaching","label":"Coaching & development","blurb":"Developing people and giving useful feedback."},{"key":"communication","label":"Communication","blurb":"Listening, informing, and keeping people in the loop."},{"key":"accountability","label":"Execution & accountability","blurb":"Holding commitments and removing obstacles."}],"items":[{"key":"dir_1","dimension":"direction","text":"I set clear goals and priorities for my team."},{"key":"dir_2","dimension":"direction","text":"My team knows how their work connects to the bigger picture."},{"key":"coach_1","dimension":"coaching","text":"I regularly coach and develop the people I manage."},{"key":"coach_2","dimension":"coaching","text":"I give timely, specific feedback — both praise and correction."},{"key":"comm_1","dimension":"communication","text":"I communicate openly and listen well."},{"key":"comm_2","dimension":"communication","text":"I keep my team informed about decisions that affect them."},{"key":"acc_1","dimension":"accountability","text":"I hold myself and others accountable for our commitments."},{"key":"acc_2","dimension":"accountability","text":"I remove obstacles so my team can do their best work."}]}$j$::jsonb
where not exists (select 1 from public.assessment_template where workspace_id is null and key='manager_skills');
